version: '3.4'

services:
  breakingnews.webapi:
    image: ${DOCKER_REGISTRY-}breakingnewswebapi
    build:
      context: .
      dockerfile: BreakingNews.WebAPI/Dockerfile
    depends_on:
      - breakingnews.postgresql
    networks:
      - breakingnews-network
  breakingnews.postgresql:
    image: postgres:15.4
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "C:/containers/postgresql-breaking-news:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: breakingnews-app-user
      POSTGRES_PASSWORD: TACfAo8RoGtv1jK6
      POSTGRES_DB: BreakingNews
    networks:
      - breakingnews-network
  breakingnews.adminer:
    image: adminer:4
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - breakingnews.postgresql
    networks:
      - breakingnews-network

networks:
  breakingnews-network:
    driver: bridge